version: '3'
services:
  hadoop:
    image: "raulmarinperez/ie_hst_hadoop3.2_vanilla"
    container_name: hadoop
    ports:
      - "8088:8088"
      - "19888:19888"
      - "50070:50070"
      - "50075:50075"
  nifi:
    image: "apache/nifi:latest"
    container_name: nifi
    ports:
      - "9090:9090"
    environment:
      NIFI_WEB_HTTP_PORT: 9090
      HADOOP_USER_NAME: root
      